server:
  port: 8082
spring:
  application:
    name: "payment-service"
  datasource:
    url: ${PAYMENT_DB_URL}
    driver-class-name: "org.postgresql.Driver"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"

axon:
  eventhandling:
    processors:
      payment-group:
        mode: subscribing
  axonserver:
    servers: localhost:8124