DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;

CREATE TABLE orders
(
    order_id        UUID PRIMARY KEY,
    status          VARCHAR(20)    NOT NULL,
    reason          VARCHAR(255),
    updated_at      TIMESTAMP,
    customer_id     UUID           NOT NULL,
    customer_name   VARCHAR(100),
    customer_email  VARCHAR(100),
    address         VARCHAR(150)   NOT NULL,
    city            VARCHAR(100)   NOT NULL,
    state           VARCHAR(100)   NOT NULL,
    zip_code        VARCHAR(5)     NOT NULL,
    payment_id      UUID,
    payment_status  VARCHAR(50),
    total_amount    DECIMAL(19, 2) NOT NULL,
    shipping_id     UUID,
    shipping_status VARCHAR(50)
);

CREATE INDEX idx_customer_id ON orders (customer_id);
CREATE INDEX idx_payment_id ON orders (payment_id);
CREATE INDEX idx_shipping_id ON orders (shipping_id);

CREATE TABLE order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id UUID           NOT NULL,
    quantity   INT            NOT NULL,
    price      DECIMAL(15, 2) NOT NULL,
    order_id   UUID           NOT NULL,
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
            REFERENCES orders (order_id)
            ON DELETE CASCADE
);

CREATE INDEX idx_order_item_order_id ON order_items (order_id);
CREATE INDEX idx_order_item_product_id ON order_items (product_id);